// required: associates our `main.dart` with the code generated by Freezed
import 'package:freezed_annotation/freezed_annotation.dart';

part 'server_error.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'server_error.g.dart';

@freezed
class ServerError with _$ServerError {
  const factory ServerError({
    required String status,
    required String error,
    required Retry retry,
  }) = _ServerError;

  factory ServerError.fromJson(Map<String, Object?> json) =>
      _$ServerErrorFromJson(json);
}

@freezed
class Retry with _$Retry {
  const factory Retry({
    required bool available,
    required int interval,
  }) = _Retry;

  factory Retry.fromJson(Map<String, Object?> json) => _$RetryFromJson(json);
}
