name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
#  pull_request:



jobs:

  analyze:
    name: Run analyzer and formatter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: generate .env
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ".env"
          FILE_DATA: "BASE_URL=${{secrets.BASE_URL}}\nTOKEN=${{secrets.API_TOKEN}}"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed .
      - name: test
        run: flutter test
        id: test
      - if: ${{ failure() && steps.test.conclusion == 'failure' }}
        name: 'Upload test failures'
        uses: actions/upload-artifact@v3
        with:
          name: test-failures
          path: test/failures
          retention-days: 5
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: flutter build apk --release
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk
  
     
